[tox]
envlist = local, kubernetes, argo

[testenv]
usedevelop = true
passenv =
    # Core Metaflow config
    METAFLOW_HOME
    METAFLOW_PROFILE
    METAFLOW_DEFAULT_METADATA
    METAFLOW_SERVICE_URL
    METAFLOW_SERVICE_INTERNAL_URL
    METAFLOW_UI_URL
    # Datastore / S3 / MinIO
    METAFLOW_DEFAULT_DATASTORE
    METAFLOW_DATASTORE_SYSROOT_S3
    AWS_CONFIG_FILE
    AWS_SHARED_CREDENTIALS_FILE
    AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY
    AWS_ENDPOINT_URL_S3
    # Kubernetes
    METAFLOW_KUBERNETES_NAMESPACE
    METAFLOW_KUBERNETES_SECRETS
    METAFLOW_KUBERNETES_JOBSET_ENABLED
    METAFLOW_KUBERNETES_CONDA_ARCH
    # Argo Events
    METAFLOW_ARGO_EVENTS_EVENT
    METAFLOW_ARGO_EVENTS_EVENT_BUS
    METAFLOW_ARGO_EVENTS_EVENT_SOURCE
    METAFLOW_ARGO_EVENTS_INTERNAL_WEBHOOK_URL
    METAFLOW_ARGO_EVENTS_SERVICE_ACCOUNT
    METAFLOW_ARGO_EVENTS_WEBHOOK_AUTH
    METAFLOW_ARGO_EVENTS_WEBHOOK_URL
    # System
    HOME
    USER
    KUBECONFIG

[testenv:local]
deps = pytest-json-report
commands =
    pytest -m local --pyargs metaflow_qa_tests -v \
           --json-report --json-report-file=test-results/local.json \
           {posargs}
commands_post =
    python scripts/merge_results.py

[testenv:kubernetes]
deps =
    kubernetes
    pytest-json-report
commands =
    pytest -m kubernetes --pyargs metaflow_qa_tests -v \
           --json-report --json-report-file=test-results/kubernetes.json \
           {posargs}
commands_post =
    python scripts/merge_results.py

[testenv:argo]
deps =
    kubernetes
    pytest-json-report
commands =
    pytest -m argo_workflows --pyargs metaflow_qa_tests -v \
           --json-report --json-report-file=test-results/argo.json \
           {posargs}
commands_post =
    python scripts/merge_results.py

[testenv:all]
deps =
    kubernetes
    pytest-json-report
commands =
    pytest -m local --pyargs metaflow_qa_tests -v \
           --json-report --json-report-file=test-results/local.json \
           {posargs}
    pytest -m kubernetes --pyargs metaflow_qa_tests -v \
           --json-report --json-report-file=test-results/kubernetes.json \
           {posargs}
    pytest -m argo_workflows --pyargs metaflow_qa_tests -v \
           --json-report --json-report-file=test-results/argo.json \
           {posargs}
commands_post =
    python scripts/merge_results.py