[tox]
envlist=local,kubernetes,argo
isolated_build= true
[testenv]
passenv=
       METAFLOW_HOME
       METAFLOW_PROFILE
       METAFLOW_SERVICE_URL
       METAFLOW_DEFAULT_METADATA
       METAFLOW_DEFAULT_DATASTORE
       METAFLOW_DATASTORE_SYSROOT_S3
       METAFLOW_KUBERNETES_NAMESPACE
       METAFLOW_KUBERNETES_SECRETS
       METAFLOW_KUBERNETES_CONDA_ARCH
       METAFLOW_KUBERNETES_JOBSET_ENABLED
       METAFLOW_SERVICE_INTERNAL_URL
       METAFLOW_SERVICE_URL
       METAFLOW_UI_URL
       METAFLOW_ARGO_EVENTS_EVENT
       METAFLOW_ARGO_EVENTS_EVENT_BUS
       METAFLOW_ARGO_EVENTS_EVENT_SOURCE
       METAFLOW_ARGO_EVENTS_INTERNAL_WEBHOOK_URL
       METAFLOW_ARGO_EVENTS_SERVICE_ACCOUNT
       METAFLOW_ARGO_EVENTS_WEBHOOK_AUTH
       METAFLOW_ARGO_EVENTS_WEBHOOK_URL

       AWS_ACCESS_KEY_ID
       AWS_SECRET_ACCESS_KEY
       AWS_ENDPOINT_URL_S3
       AWS_CONFIG_FILE
       HOME
       USER

[testenv:local]
commands=pytest -m local --pyargs metaflow_qa_tests -v {posargs}

[testenv:kubernetes]
commands=pytest -m kubernetes --pyargs metaflow_qa_tests -v {posargs}

[testenv:argo]
commands=pytest -m argo_workflows --pyargs metaflow_qa_tests -v {posargs}

[testenv:all]
commands=pytest --pyargs metaflow_qa_tests -v {posargs}
